<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script src="{{ asset('assets/frontend/vendor/pie-chart.js') }}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script src="{{ asset('assets/backend/vendor/jquery.mask.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script src="{{ asset('assets/frontend/vendor/jquery.mask.js') }}"></script>
<script src="{{ asset('assets/frontend/js/main-alpha.js') }}"></script>
<script src="{{ asset('assets/frontend/js/main-bravo.js') }}"></script>
<script src="{{ asset('assets/frontend/js/main-charlie.js') }}"></script>
<script src="{{ asset('assets/frontend/js/main-delta.js') }}"></script>
<script src="{{ asset('assets/frontend/js/auth.js') }}"></script>
<script src="{{ asset('assets/frontend/js/app.js') }}"></script>
